In [4]:
import pandas as pd
archivo_csv = "df_sucio.csv"
df = pd.read_csv(archivo_csv)
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23.0,84.0,Low,NaN,NaN,7.0,73.0,Low,NaN,0.0,Low,Medium,Public,Positive,3.0,No,High School,Near,Male,NaN
1,19.0,64.0,Low,Medium,No,8.0,59.0,Low,Yes,2.0,Medium,Medium,Public,Negative,4.0,No,College,Moderate,Female,61.0
2,24.0,NaN,Medium,Medium,Yes,7.0,91.0,Medium,Yes,2.0,Medium,Medium,Public,Neutral,4.0,No,Postgraduate,Near,Male,74.0
3,29.0,89.0,Low,Medium,Yes,8.0,98.0,Medium,Yes,1.0,Medium,Medium,Public,Negative,4.0,No,High School,Moderate,Male,71.0
4,19.0,92.0,Medium,Medium,Yes,6.0,65.0,Medium,Yes,NaN,Medium,High,Public,Neutral,4.0,No,College,Near,Female,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7048,17.0,90.0,High,Medium,No,8.0,82.0,Medium,Yes,0.0,Medium,High,Public,Neutral,4.0,No,College,Near,Male,70.0
7049,12.0,67.0,Medium,High,NaN,8.0,77.0,Medium,Yes,2.0,Low,High,Private,Positive,3.0,No,College,Near,Male,64.0
7050,28.0,60.0,Medium,High,Yes,7.0,NaN,Low,Yes,3.0,Low,Medium,Private,Neutral,3.0,No,High School,Near,Female,65.0
7051,30.0,70.0,Low,Medium,No,8.0,75.0,NaN,Yes,1.0,Medium,NaN,Private,NaN,2.0,No,High School,Near,Female,67.0
7052,11.0,90.0,Low,Low,Yes,8.0,59.0,Low,Yes,1.0,Low,High,Public,Positive,4.0,No,High School,Near,Male,64.0

In [144]:
df.columns

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='object')

In [2]:
df.isnull().sum()

Hours_Studied                 352
Attendance                    352
Parental_Involvement          352
Access_to_Resources           352
Extracurricular_Activities    352
Sleep_Hours                   361
Previous_Scores               352
Motivation_Level              352
Internet_Access               352
Tutoring_Sessions             352
Family_Income                 352
Teacher_Quality               433
School_Type                   352
Peer_Influence                352
Physical_Activity             352
Learning_Disabilities         352
Parental_Education_Level      442
Distance_from_Home            418
Gender                        352
Exam_Score                    363
dtype: int64

In [5]:
columnas_a_limpiar = [
    "Attendance",
    "Sleep_Hours",
    "Previous_Scores",
    "Tutoring_Sessions",
    "Physical_Activity",
    "Exam_Score","Hours_Studied",]

In [6]:
for columna in columnas_a_limpiar:
    df[columna] = df[columna].replace(" ", 0)
    df[columna] = df[columna].fillna(0)

In [7]:
colText = [
    "Parental_Involvement",
    "Access_to_Resources",
    "Extracurricular_Activities",
    "Motivation_Level",
    "Internet_Access",
    "Teacher_Quality",
    "School_Type",
    "Peer_Influence",
    "Learning_Disabilities",
    "Parental_Education_Level",
    "Gender","Distance_from_Home","Family_Income"
]

In [8]:
for columna in colText:
    df[columna] = df[columna].fillna("Desconocido")
    df[columna] = df[columna].str.strip()

In [149]:
df.isnull().sum()

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Family_Income                 0
Teacher_Quality               0
School_Type                   0
Peer_Influence                0
Physical_Activity             0
Learning_Disabilities         0
Parental_Education_Level      0
Distance_from_Home            0
Gender                        0
Exam_Score                    0
dtype: int64

In [9]:
df.columns = df.columns.str.replace("Hours_Studied", "Horas_Estudio")
df.columns = df.columns.str.replace("Attendance", "Asistencia")
df.columns = df.columns.str.replace("Parental_Involvement", "Involucramiento_Padres")
df.columns = df.columns.str.replace("Access_to_Resources", "Acceso_a_Recursos")
df.columns = df.columns.str.replace("Extracurricular_Activities", "Actividades_Extracurriculares")
df.columns = df.columns.str.replace("Sleep_Hours", "Horas_SueÃ±o")
df.columns = df.columns.str.replace("Previous_Scores", "Puntajes_Anteriores")
df.columns = df.columns.str.replace("Motivation_Level", "Nivel_Motivacion")
df.columns = df.columns.str.replace("Internet_Access", "Acceso_a_Internet")
df.columns = df.columns.str.replace("Tutoring_Sessions", "Sesiones_Tutorias")
df.columns = df.columns.str.replace("Family_Income", "Ingreso_Familiar")
df.columns = df.columns.str.replace("Teacher_Quality", "Calidad_Maestro")
df.columns = df.columns.str.replace("School_Type", "Tipo_Escuela")
df.columns = df.columns.str.replace("Peer_Influence", "Influencias_CompaÃ±eros")
df.columns = df.columns.str.replace("Physical_Activity", "Actividad_Fisica")
df.columns = df.columns.str.replace("Learning_Disabilities", "Discapacidad_de_Aprendizaje")
df.columns = df.columns.str.replace("Parental_Education_Level", "Nivel_Educacion_Padres")
df.columns = df.columns.str.replace("Distance_from_Home", "Distancia_Hogar")
df.columns = df.columns.str.replace("Gender", "Genero")
df.columns = df.columns.str.replace("Exam_Score", "Puntaje_Examen")

In [10]:
df['Genero'] = df['Genero'].replace({'Male': 'Masculino', 'Female': 'Femenino'})
df['Nivel_Motivacion'] = df['Nivel_Motivacion'].replace({'High': 'Alta', 'Low': 'Baja', 'Medium': 'Media'})
df['Calidad_Maestro'] = df['Calidad_Maestro'].replace({'High': 'Alta', 'Low': 'Baja', 'Medium': 'Media'})
df['Ingreso_Familiar'] = df['Ingreso_Familiar'].replace({'High': 'Alta', 'Low': 'Baja', 'Medium': 'Media'})
df['Acceso_a_Recursos'] = df['Acceso_a_Recursos'].replace({'High': 'Alta', 'Low': 'Baja', 'Medium': 'Media'})
df['Involucramiento_Padres'] = df['Involucramiento_Padres'].replace({'High': 'Alta', 'Low': 'Baja', 'Medium': 'Media'})
df['Distancia_Hogar'] = df['Distancia_Hogar'].replace({'Far': 'Lejos', 'Near': 'Cerca', 'Moderate': 'Moderado'})
df['Influencias_CompaÃ±eros'] = df['Influencias_CompaÃ±eros'].replace({'Positive': 'Positivo', 'Negative': 'Negativa'})
df['Tipo_Escuela'] = df['Tipo_Escuela'].replace({'Public': 'Publica', 'Private': 'Privada'})
df['Acceso_a_Internet'] = df['Acceso_a_Internet'].replace({'Yes': 'Si'})
df['Discapacidad_de_Aprendizaje'] = df['Discapacidad_de_Aprendizaje'].replace({'Yes': 'Si'})
df['Actividades_Extracurriculares'] = df['Actividades_Extracurriculares'].replace({'Yes': 'Si'})
df['Nivel_Educacion_Padres'] = df['Nivel_Educacion_Padres'].replace({'College': 'Universidad', 'High School': 'Preparatoria', 'Postgraduate': 'Posgrado'})

In [155]:
df.columns

Index(['Horas_Estudio', 'Asistencia', 'Involucramiento_Padres',
       'Acceso_a_Recursos', 'Actividades_Extracurriculares', 'Horas_SueÃ±o',
       'Puntajes_Anteriores', 'Nivel_Motivacion', 'Acceso_a_Internet',
       'Sesiones_Tutorias', 'Ingreso_Familiar', 'Calidad_Maestro',
       'Tipo_Escuela', 'Influencias_CompaÃ±eros', 'Actividad_Fisica',
       'Discapacidad_de_Aprendizaje', 'Nivel_Educacion_Padres',
       'Distancia_Hogar', 'Genero', 'Puntaje_Examen'],
      dtype='object')

In [11]:
df

,Horas_Estudio,Asistencia,Involucramiento_Padres,Acceso_a_Recursos,Actividades_Extracurriculares,Horas_SueÃ±o,Puntajes_Anteriores,Nivel_Motivacion,Acceso_a_Internet,Sesiones_Tutorias,Ingreso_Familiar,Calidad_Maestro,Tipo_Escuela,Influencias_CompaÃ±eros,Actividad_Fisica,Discapacidad_de_Aprendizaje,Nivel_Educacion_Padres,Distancia_Hogar,Genero,Puntaje_Examen
0,23.0,84.0,Baja,Desconocido,Desconocido,7.0,73.0,Baja,Desconocido,0.0,Baja,Media,Publica,Positivo,3.0,No,Preparatoria,Cerca,Masculino,0.0
1,19.0,64.0,Baja,Media,No,8.0,59.0,Baja,Si,2.0,Media,Media,Publica,Negativa,4.0,No,Universidad,Moderado,Femenino,61.0
2,24.0,0,Media,Media,Si,7.0,91.0,Media,Si,2.0,Media,Media,Publica,Neutral,4.0,No,Posgrado,Cerca,Masculino,74.0
3,29.0,89.0,Baja,Media,Si,8.0,98.0,Media,Si,1.0,Media,Media,Publica,Negativa,4.0,No,Preparatoria,Moderado,Masculino,71.0
4,19.0,92.0,Media,Media,Si,6.0,65.0,Media,Si,0,Media,Alta,Publica,Neutral,4.0,No,Universidad,Cerca,Femenino,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7048,17.0,90.0,Alta,Media,No,8.0,82.0,Media,Si,0.0,Media,Alta,Publica,Neutral,4.0,No,Universidad,Cerca,Masculino,70.0
7049,12.0,67.0,Media,Alta,Desconocido,8.0,77.0,Media,Si,2.0,Baja,Alta,Privada,Positivo,3.0,No,Universidad,Cerca,Masculino,64.0
7050,28.0,60.0,Media,Alta,Si,7.0,0,Baja,Si,3.0,Baja,Media,Privada,Neutral,3.0,No,Preparatoria,Cerca,Femenino,65.0
7051,30.0,70.0,Baja,Media,No,8.0,75.0,Desconocido,Si,1.0,Media,Desconocido,Privada,Desconocido,2.0,No,Preparatoria,Cerca,Femenino,67.0
7052,11.0,90.0,Baja,Baja,Si,8.0,59.0,Baja,Si,1.0,Baja,Alta,Publica,Positivo,4.0,No,Preparatoria,Cerca,Masculino,64.0

In [12]:
df.to_csv("df_limpio.csv", index=False)